# Site Settings
title:               汽车驾驶学员的理论培训
tagline:             
description:
baseurl:            #"/Lagrange"
url:                #"https://lenpaul.github.io"
github:
  url:               #"https://lenpaul.github.io/Lagrange"
author:
  name:              "Russell Mo"
  email:             "httpmo@gmail.com"
navigation:
- title: About
  url: /about

paginate:            5
disqus:              #"your-disqus"

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
gems:                [jekyll-paginate]
